name: Create Release

on:
  push:
    branches:
      - main
      - beta

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine bump options
        id: logic
        run: |
          VER=`git describe --tags --abbrev=0 --match 'v*.*.*'`
          BRANCH=`git branch --show-current`
          pre=
          [ ${VER%%.*} = v0 ] && grep -q '^#\s*stable\b' cog.toml && bump=major || bump=auto
          main=`sed -nr '/^#\s*main\s*=\s*(.*?)\s*$/{s//\1/p;q}' cog.toml`
          if [ "$BRANCH" != "${main:-main}" ]; then
            pre=`git describe --tags --abbrev=0 --match "${VER%%-*}-$BRANCH.*"`
            pre=${pre##*.} pre=$BRANCH.$(( pre + 1 ))
          fi
          echo "opts=--$bump${pre:+ --pre $pre}" >> $GITHUB_OUTPUT

      - name: Semantic versioning release
        uses: cocogitto/cocogitto-action@main
        env:
          GH_TOKEN: ${{ github.token }}
        with:
          command: bump
          args: ${{ steps.logic.outputs.opts }}

