name: Create Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine bump type
        id: bump_logic
        run: |
          { rm .major 2>/dev/null && echo type=major || echo type=auto; } >> $GITHUB_OUTPUT

      - name: Semantic Versioning Release
        id: bump
        uses: cocogitto/cocogitto-action@main
        with:
          command: bump
          args: --${{ steps.bump_logic.outputs.type }} --skip-untracked

      - name: Generate Changelog for this release
        id: changelog
        if: "!contains(steps.bump.outputs.stdout, 'No conventional commits')"
        uses: cocogitto/cocogitto-action@main
        with:
          command: changelog
          args: --at ${{ steps.bump.outputs.version }}

      - name: Upload Release to GitHub
        if: "!contains(steps.bump.outputs.stdout, 'No conventional commits')"
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.changelog.outputs.stdout }}
          tag_name: ${{ steps.bump.outputs.version }}

#        if: !contains(steps.bump.outputs.stdout, 'No conventional commits')

#      - name: Update floating major tag
#        if: "!contains(steps.bump.outputs.stdout, 'No conventional commits')"
#        run: |
#          TAG=${{ steps.bump.outputs.version }} TAG=${TAG%%.*}
#          git tag -f "$TAG"
#          git push -f origin "$TAG"

#        if: contains(steps.bump.outputs.version, '.')
