on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Semantic Versioning Release
        id: bump
        uses: cocogitto/cocogitto-action@main
        with:
          command: bump
          args: --auto

      - name: Generate Changelog for this release
        id: changelog
        uses: cocogitto/cocogitto-action@main
        with:
          command: changelog
          args: --at ${{ steps.bump.outputs.version }}

      - name: Upload release to 
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.release.outputs.stdout }}
          tag_name: ${{ steps.bump.outputs.version }}
          generate_release_notes: false
