on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Semantic Versioning Release
        id: bump
        uses: cocogitto/cocogitto-action@main
        with:
          command: bump
          args: --auto

      - name: Generate Changelog for this release
        id: changelog
        if: steps.bump.outputs.version != ''
        uses: cocogitto/cocogitto-action@main
        with:
          command: changelog
          args: --at ${{ steps.bump.outputs.version }}

      - name: Upload Release to GitHub
        if: steps.bump.outputs.version != ''
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.changelog.outputs.stdout }}
          tag_name: ${{ steps.bump.outputs.version }}

      - name: Update floating major tag
        if: steps.bump.outputs.version != ''
        run: |
          TAG=${{ steps.bump.outputs.version }} TAG=${TAG%%.*}
          git tag -f "${TAG#v}"
          git push -f origin "${TAG#v}"
