name: Create Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Semantic Versioning Release
        id: bump
        uses: cocogitto/cocogitto-action@main
        run: cog bump --`[ -f .major ] && rm .major && echo major || echo auto`

#          test -f .major && rm .major && bump=major || bump=auto
#          cog bump --$bump
#        with:
#          command: bump
#          args: --auto

      - name: Generate Changelog for this release
        id: changelog
        if: contains(steps.bump.outputs.version, '.')
        uses: cocogitto/cocogitto-action@main
        with:
          command: changelog
          args: --at ${{ steps.bump.outputs.version }}

      - name: Upload Release to GitHub
        if: contains(steps.bump.outputs.version, '.')
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.changelog.outputs.stdout }}
          tag_name: ${{ steps.bump.outputs.version }}

      - name: Update floating major tag
        if: contains(steps.bump.outputs.version, '.')
        run: |
          TAG=${{ steps.bump.outputs.version }} TAG=${TAG%%.*}
          git tag -f "$TAG"
          git push -f origin "$TAG"
